ktor {
    deployment {
        port = 8081
        host = "0.0.0.0"
    }
}

benchmark {
    database {
        r2dbcUrl = "r2dbc:postgresql://localhost:5432/benchmark"
        username = "benchmark"
        password = "benchmark"
        applicationName = "ktor-r2dbc-benchmark"
        initialPoolSize = 16
        maxPoolSize = 64
    }
    logging {
        httpCalls = false
    }
}
