spring:
  application:
    name: spring-webflux-r2dbc-benchmark
  r2dbc:
    url: ${SPRING_R2DBC_URL:r2dbc:postgresql://localhost:5432/benchmark?applicationName=spring-webflux-r2dbc-benchmark}
    username: ${SPRING_R2DBC_USERNAME:benchmark}
    password: ${SPRING_R2DBC_PASSWORD:benchmark}
    pool:
      enabled: true
      initial-size: ${SPRING_R2DBC_POOL_INITIAL_SIZE:16}
      max-size: ${SPRING_R2DBC_POOL_MAX_SIZE:64}

management:
  endpoints:
    web:
      exposure:
        include: health

server:
  port: ${SERVER_PORT:8082}
