ktor {
  deployment {
    port = 8083
    host = "0.0.0.0"
  }
}

benchmark {
  database {
    jdbcUrl = "jdbc:postgresql://localhost:5432/benchmark?ApplicationName=ktor-jdbc-benchmark"
    username = "benchmark"
    password = "benchmark"
    maxPoolSize = 32
  }
  logging {
    httpCalls = false
  }
}

